### ISSUE TITLE
Any nuget package?

### ISSUE THREAD

**Issue by PieroCastillo** [arklumpus/AvaloniaColorPicker#1]

**Comment by arklumpus** [comment]
Yes, it's here: https://www.nuget.org/packages/AvaloniaColorPicker/ . To get it to show in the NuGet manager in Visual Studio, you need to check "Include prerelease" (the package references the Avalonia 0.10.0-preview6 prerelease package, therefore it must be marked as a prerelease as well).

**Comment by PieroCastillo** [comment]
thanks u!, this is the more complete colorpicker for avalonia what I saw!
