### ISSUE TITLE
Would you consider a more flexible license

### ISSUE THREAD

**Issue by timothyparez** [arklumpus/AvaloniaColorPicker#2]
Hi,
Would you consider changing the license to MIT (like AvaloniaUI) or  
at the very least to LGPL3 so that this can be used in non-GPL projects?

**Comment by arklumpus** [comment]
Hi, thank you for suggesting this! I have been thinking about it, and I will re-release the library under LGPL (as soon as I manage to replace the license notices everywhere). I will close the issue when I do that!

**Comment by arklumpus** [comment]
Done!

**Comment by timothyparez** [comment]
Thank you, that is awesome!
