### ISSUE TITLE
Slightly Confused About Binding

### ISSUE THREAD

**Issue by jamsoft** [arklumpus/AvaloniaColorPicker#7]
Why make PreviousColour bindable on ColorPicker, But Color isn't bindable?

Or am I missing something?

**Comment by arklumpus** [comment]
Hi! The issue was that the `Color` doesn't really exist as such but is instead created when you access the property. I have now shifted some things around, and it seems to be working OK as a `StyledProperty` (and hence bindable) in version 1.3.3.

**Comment by jamsoft** [comment]
Excellent!
